// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bully_Chat_FullMethodName = "/Bully/Chat"
)

// BullyClient is the client API for Bully service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BullyClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type bullyClient struct {
	cc grpc.ClientConnInterface
}

func NewBullyClient(cc grpc.ClientConnInterface) BullyClient {
	return &bullyClient{cc}
}

func (c *bullyClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bully_ServiceDesc.Streams[0], Bully_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bully_ChatClient = grpc.BidiStreamingClient[Message, Message]

// BullyServer is the server API for Bully service.
// All implementations must embed UnimplementedBullyServer
// for forward compatibility.
type BullyServer interface {
	Chat(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedBullyServer()
}

// UnimplementedBullyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBullyServer struct{}

func (UnimplementedBullyServer) Chat(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedBullyServer) mustEmbedUnimplementedBullyServer() {}
func (UnimplementedBullyServer) testEmbeddedByValue()               {}

// UnsafeBullyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BullyServer will
// result in compilation errors.
type UnsafeBullyServer interface {
	mustEmbedUnimplementedBullyServer()
}

func RegisterBullyServer(s grpc.ServiceRegistrar, srv BullyServer) {
	// If the following call pancis, it indicates UnimplementedBullyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bully_ServiceDesc, srv)
}

func _Bully_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BullyServer).Chat(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bully_ChatServer = grpc.BidiStreamingServer[Message, Message]

// Bully_ServiceDesc is the grpc.ServiceDesc for Bully service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bully_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bully",
	HandlerType: (*BullyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Bully_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto.proto",
}
